apiVersion: v1
kind: ServiceAccount
metadata:
  name: gdrdrv
  namespace: openshift-sro
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gdrdrv
  namespace: openshift-sro
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gdrdrv
  namespace: openshift-sro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gdrdrv
  namespace: openshift-sro
subjects:
- kind: ServiceAccount
  name: gdrdrv
  namespace: openshift-sro
userNames:
- system:serviceaccount:openshift-sro:gdrdrv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gdrdrv
  namespace: openshift-sro
data:
  oci-nvidia-hook-json: | 
    {
        "version": "1.0.0",
        "hook": {
            "path": "/run/nvidia/driver/usr/bin/nvidia-container-toolkit",
            "args": ["nvidia-container-runtime-hook", "prestart"],
            "env": [
                "PATH=/run/nvidia/driver/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ]
        },
        "when": {
            "always": true,
            "commands": [".*"]
        },
        "stages": ["prestart"]
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: gdrdrv-daemonset
  name: gdrdrv-daemonset
  namespace: openshift-sro
  annotations:
    openshift.io/scc: gdrdrv
    callback: gdrdrv-daemonset
spec:
  selector:
    matchLabels:
      app: gdrdrv-daemonset
  template:
    metadata:
      # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
      # reserves resources for critical add-on pods so that they can be rescheduled after
      # a failure.  This annotation works in tandem with the toleration below.
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: gdrdrv-daemonset
    spec:
      tolerations:
      - operator: Exists
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      serviceAccount: gdrdrv
      serviceAccountName: gdrdrv
      hostPID: true
      containers:
      - image: quay.io/openshift-psap/gdrdrv
        imagePullPolicy: Always
        name: gdrdrv-ctr
        command: ["sleep infinity"]
        securityContext:
          privileged: true
#        volumeMounts:
#          - name: run-nvidia
#            mountPath: /run/nvidia
#            mountPropagation: Bidirectional
#          - name: host-hooks
#            mountPath: /host/etc/containers/oci
#          - name: config
#           mountPath: /etc/containers/oci/hooks.d
#         - name: host-modules
#            mountPath: /host/lib/modules
#      volumes:
#        - name: host-hooks
#          hostPath:
#            path: /etc/containers/oci
#        - name: host-modules
#          hostPath:
#            path: /lib/modules
#        - name: run-nvidia
#          hostPath:
#            path: /run/nvidia
#       - name: config
#         configMap:
#           name: gdrdrv
#            items:
#              - key: oci-nvidia-hook-json
#                path: oci-nvidia-hook.json
      nodeSelector:
        node-role.kubernetes.io/worker: ""
        feature.node.kubernetes.io/pci-10de.present: "true"

