apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-kargs-worker
spec:
  kernelArguments:
    - default_hugepagesz=1G
      hugepagesz=1G
      hugepages=6 