apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: topology-cpu-manager-enabled
spec:
  machineConfigPoolSelector:
    matchLabels:
      custom-kubelet: enabled
  kubeletConfig:
    cpuManagerPolicy: static
    cpuManagerReconcilePeriod: 5s
    topologyManagerPolicy: single-numa-node



