apiVersion: v1
kind: ServiceAccount
metadata:
  name: perf-tools
  namespace: openshift-sro
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: perf-tools
  namespace: openshift-sro
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: perf-tools
  namespace: openshift-sro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: perf-tools
  namespace: openshift-sro
subjects:
- kind: ServiceAccount
  name: perf-tools
  namespace: openshift-sro
userNames:
- system:serviceaccount:openshift-sro:perf-tools
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: perf-tools-entrypoint
  namespace: openshift-sro
data:
  entrypoint.sh: |-
    #!/bin/bash
    sleep infinity
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: perf-tools-daemonset
  name: perf-tools-daemonset
  namespace: openshift-sro
  annotations:
    openshift.io/scc: perf-tools
    callback: perf-tools-daemonset
spec:
  selector:
    matchLabels:
      app: perf-tools-daemonset
  template:
    metadata:
      # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
      # reserves resources for critical add-on pods so that they can be rescheduled after
      # a failure.  This annotation works in tandem with the toleration below.
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: perf-tools-daemonset
    spec:
      tolerations:
      - operator: Exists
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      serviceAccount: perf-tools
      serviceAccountName: perf-tools
      hostPID: true
      hostNetwork: true
      hostIPC: true
      hostPorts: true
      containers:
      - image: quay.io/openshift-psap/perf-tools
        imagePullPolicy: Always
        name: perf-tools-ctr
        command: ["/bin/entrypoint.sh"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: entrypoint
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
        - name: devices
          mountPath: /dev
        - name: proc
          mountPath: /proc
        - name: sys
          mountPath: /sys
        - name: modules
          mountPath: /host/lib/modules
      volumes:
      - name: devices
        hostPath: 
          path: /dev
      - name: proc
        hostPath: 
          path: /proc
      - name: sys
        hostPath: 
          path: /sys
      - name: modules
        hostPath:
          path: /lib/modules

      - name: entrypoint
        configMap:
          defaultMode: 0700
          name: perf-tools-entrypoint
      nodeSelector:
        node-role.kubernetes.io/worker: ""
        feature.node.kubernetes.io/pci-10de.present: "true"

